version: '3'

services:
  ntopng:
    container_name: ntopng
    image: ntop/ntopng_arm64.dev:latest
    volumes:
      - data:/var/lib/ntopng
      - ./pcap:/pcap
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Rome
    command:
      - "--community"
      - "-i /pcap/testFifo"
    ports:
      - 80:3000
    networks:
      - proxy

  test:
    container_name: test
    build: ./test
    volumes:
      - ./pcap:/pcap
      
volumes:
  data:


networks:
  proxy:
    external: true