version: '3'

services:
  ntopng:
    container_name: ntopng
    build: ./ntopng
    volumes:
      - data:/var/lib/ntopng
      - ./pcap:/pcap
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Rome
      - NETWORK_INTERFACES=${NETWORK_INTERFACES}
      - LOCAL_NETWORKS=${LOCAL_NETWORKS}
    ports:
      - 80:3000
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - fritzpcap

  fritzpcap:
    container_name: fritzpcap
    build: ./fritzpcap
    environment:
      - FRITZIP=${FRITZIP}
      - FRITZUSER=${FRITZUSER}
      - FRITZPWD=${FRITZPWD}
      - NETWORK_INTERFACES=${NETWORK_INTERFACES}
      - INTERFACE_URL_PARAMS=${INTERFACE_URL_PARAMS}
      - LOCAL_NETWORKS=${LOCAL_NETWORKS}
    volumes:
      - ./pcap:/pcap
    restart: unless-stopped

volumes:
  data:


networks:
  proxy:
    external: true